### ISSUE TITLE
cleverbutts.js Invalid Character Line 15 Char 22

### ISSUE THREAD

**Issue by ImaginaryPal** [SplitPixl/Cleverbutts#28]
Invalid Character Script cannot be ran

Cleverbutts.js
Line : 15
Char : 22
Error : Invalid Character
Code: 800A03F6

**Comment by DrewTheGhost** [comment]
Run with node.js, not Microsoft's.

**Comment by ImaginaryPal** [comment]
Got ya thank you.. When trying to run startClever.bat I get
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: missing path
    at Module.require (module.js:496:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Willi\Documents\Cleverbutts\CB-CLI\cleverbutts.js:4:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)

Is there any way to fix this? Ive followed the classic install Step by step

**Comment by DrewTheGhost** [comment]
This is a new error that just popped up, looking in to it. Will get back to you when a fix is found. I'm Drew on the Cleverbutts server if you want to find me there.

**Comment by ImaginaryPal** [comment]
Ok thank you man

**Comment by SplitPixl** [comment]
This issue isn't officially fixed so I'm not going to close this issue, but it's not present in the GUI setup. Try downloading and running the [Cleverbutts Setup EXE](https://github.com/Cleverbutts/Cleverbutts/releases/download/0.1/CleverbuttsSetup.exe).
