### ISSUE TITLE
Getting a "Authentication failed" error when running bot

### ISSUE THREAD

**Issue by purperinos** [SplitPixl/Cleverbutts#5]
I'm trying to run the bot on my OS X, I don't have any windows computers lying around so I can only run it on my old macbook at the moment. I have no experience in programming or whatsoever but I'm pretty sure I followed the steps correctly.

**Terminal:**

```
USERNAME:~ USERNAME$ /Users/USERNAME/Documents/Bots/Cleverbutts/startClever.command ; exit;
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Authentication failed
    at WebSocket.websocket.onclose (/Users/USERNAME/node_modules/discord.js/lib/Client/InternalClient.js:93:1406)
    at WebSocket.onClose (/Users/USERNAME/node_modules/ws/lib/WebSocket.js:446:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (/Users/USERNAME/node_modules/ws/lib/WebSocket.js:950:8)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

The error just loops over and over in terminal and sometimes says Error: Invalid Session.

**Comment by purperinos** [comment]
This is my start script
node /Users/USERNAME/Documents/Bots/Cleverbutts/cleverbutts.js

**Comment by bigbeau** [comment]
I'm getting the exact same thing and have no idea what to do to fix it

**Comment by SplitPixl** [comment]
I know about this issue and am working on a fix.

**Comment by purperinos** [comment]
Works now after doing the temp auth fix after looking at the cleverbutts discord server.

**Comment by ghost** [comment]
How about porting cleverbutts to Eris or something else because discord.js having problems because discord API changes

**Comment by ghost** [comment]
That should fix problem 👍
